platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'HouseMatching' do
  use_frameworks! :linkage => :static

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  # Ensure only one version of react-native-gesture-handler is used
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  # Update RCT-Folly dependency
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

  use_flipper!({ 'Flipper' => '0.125.0' })
  post_install do |installer|
    react_native_post_install(installer)

    # Resolve version conflict for react-native-gesture-handler
    installer.pods_project.targets.each do |target|
      if target.name == 'RNGestureHandler'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end

    # Apply patch to RCT-Folly Time.h
    system("patch -p1 < ../patches/rct-folly-time-h.patch")
  end
end