platform :ios, '12.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'HouseMatching' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'HouseMatchingTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.125.0' })
  post_install do |installer|
    react_native_post_install(installer)
  end
end